apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  labels:
    app: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
      - name: ping-pong-app
        image: p3xu/pingpong-app:v0.1
        ports:
        - containerPort: 8080
